trydjango1/restaurants/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from .views import (
    RestaurantListView, RestaurantCreateView, RestaurantDetailView, TemplateView

)
app_name='restaurants'

urlpatterns = [
    path('', RestaurantListView.as_view(), name='list'),
    path('create/', RestaurantCreateView.as_view(), name='create'),
    path('<slug>/', RestaurantDetailView.as_view(), name='detail'),

]

trydjango1/trydjango1/urls.py
from django.contrib import admin
from django.urls import path,include
from restaurants.views import restaurant_listview, TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from restaurants.views import (
    restaurant_listview,
    RestaurantListView, RestaurantCreateView, RestaurantDetailView, restaurant_createview

)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'),name='home'),
    path('restaurants/', include('restaurants.urls',namespace='restaurants')),# this include allows for url file in apps
    path('login/', LoginView.as_view(), name='login'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetDoneView.as_view(), name='password_reset_complete'),
    # path('restaurants/', RestaurantListView.as_view(),name='restaurants'),
    # path('restaurants/create/', RestaurantCreateView.as_view(),name='restaurants-create'),
    # path('restaurants/<slug>', RestaurantListView.as_view()),
    # path('restaurants/<slug>/', RestaurantDetailView.as_view(),name='restaurant_detail'),
    path('about/', TemplateView.as_view(template_name='About.html'),name='about'),
    path('contact/', TemplateView.as_view(template_name='Contact.html'),name='contact'),
]

trydjango1/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

trydjango1/templates/snippets/js.html
<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
<!-- Latest compiled and minified JavaScript -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

trydjango1/templates/snippets/nav.html
<div class="container">
    <h1>MuyPicky.com</h1>
    <a href="{%url 'home'%}">Home</a>
    <a href="{%url 'about'%}">About</a>
    <a href="{%url 'contact'%}">Contact</a>
    <a href="{%url 'restaurants:list'%}">Detail</a>
</div>

trydjango1/templates/snippets/sidebar.html
<ul>
    <li>Item1</li>
    <li>Item2</li>
    <li>Item3</li>

</ul>